# @format

name: "React CD Pipeline"

on:
    workflow_run:
        workflows: ["React CI Workflow"]
        types:
            - completed
    workflow_dispatch:





jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: "Installing node"
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: "Setup vercel cli"
        run: npm install -g vercel

      - name: "Download build files"
        uses: actions/download-artifact@v4
        with:
          name: build
          run-id: ${{github.event.workflow_run.id}}
          github-token: ${{github.token}}

      - name: "Deploy to vercel"
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm --name=cicdproject
