name: "React CI Workflow"

on:
    push:
        branches:
            - main
            - master

jobs:
    node-setup:
        runs-on: ubuntu-latest
        steps:
            - name: "Installing node"
              uses: actions/setup-node@v4
              with:
                node-version: '24'
        
            - name: "Node version"
              run: node --version

            - name: "Clone repository"
              uses: actions/checkout@v2

            - name: "Install dependencies"
              run: npm install

            - name: "List directories of project"
              run: ls -l

            - name: "Upload artifact"
              uses: actions/upload-artifact@v4
              with:
                  name: build
                  path: dist



              


